[package]
name = "petr-pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.15.1"
blake3 = "1.5.2"
dirs = "5.0.1"
git2 = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
petr-fmt = { path = "../petr-fmt" }
thiserror = "1.0.61"
termcolor = "1.4.1"
