[package]
name = "petr-manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
petr-fmt = { path = "../petr-fmt" }
petr-pkg = { path = "../petr-pkg" }
toml = "0.8.14"
