imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
blank_lines_upper_bound = 1
fn_params_layout = "Vertical"
indent_style = "Visual"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
struct_field_align_threshold = 10
enum_discrim_align_threshold = 10
