[package]
name = "wasm-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
petr-api = { path = "../petr-api", default-features = false, features = ["no_std"] }

[lib]
crate-type = [ "rlib", "cdylib" ]
