[package]
name = "petr-stdlib"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

description = "the petr language's standard library"
license.workspace = true

[dependencies]
