[package]
name = "swim-manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
swim-fmt = { path = "../swim-fmt" }
swim-pkg = { path = "../swim-pkg" }
toml = "0.8.14"
