[package]
name = "petr-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
miette = { version = "5.10" }

[features]
debug = ["lazy_static"]
