[package]
name = "swim-typecheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swim-ast = { path = "../swim-ast" }
polytype = "7.0.1"
