name: Create issues for TODOs
on:
  push:
    branches: 
      - main

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  check_todos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: todo-issue
      uses: DerJuulsn/todo-issue@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.PROJECTS_SECRET }}
