name: TODO check
on:
  pull_request: { branches: "*" }
  push: { branches: "main" }
env:
  PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
permissions:
  contents: read
  issues: write

jobs:
  check_todos:
    runs-on: ubuntu-latest
    steps:
    - name: TODO to Issue
      uses: alstr/todo-to-issue-action@v4.13.1
      with:
        TOKEN: ${{ secrets.PROJECTS_SECRET }}
